### ISSUE TITLE
Project run errors

### ISSUE THREAD

**Issue by MaryyRuthie** [ogencoglu/fair_cyberbullying_detection#12]
When attempting to run this project (fair_cyberbullying_detection) , I'm experiencing multiple issues primarily due to outdated packages. I'm seeking assistance in updating or resolving these dependency conflicts to ensure seamless execution.
Thanks!

**Comment by ogencoglu** [comment]
Thanks for your interest!

The exact library versions are denoted in `requirements.txt`, exactly for that reason.

**Comment by MaryyRuthie** [comment]
Thank you, it's all set now; nice work!
